[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.10.11"
borsh = "0.9.3"
borsh-derive = "0.9.1"

[lib]
crate-type = ["cdylib", "lib"]
